#!/usr/bin/env python3
"""Embed openbv's own UI assets in the module: writes src/port/embedded_assets.c.

The files under assets/ that replace game files (assets/fonts/babo.tga -> main/fonts/babo.tga) are
white RGBA TGAs whose picture is all in the alpha channel. They are stored as their size plus the
alpha channel run-length encoded (count, value byte pairs, counts up to 255), and src/port/fs_gasm.c
rebuilds the TGA when the game opens the file, ahead of the game's own data. Every runner (gasm-run,
the bundles, the browser) then gets the same files without passing anything.

Needs Pillow (see bake_font.py). Usage: .deps/py/bin/python tools/fonts/embed_assets.py

This file is part of openbv, under the GNU General Public License v3 or later.
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# asset in this repository -> the game file it stands in for
FILES = [("assets/fonts/babo.tga", "main/fonts/babo.tga")]


def rle(data):
    out, i = bytearray(), 0
    while i < len(data):
        v, n = data[i], 1
        while i + n < len(data) and data[i + n] == v and n < 255:
            n += 1
        out += bytes([n, v])
        i += n
    return bytes(out)


def main():
    lines = [
        "/* Generated by tools/fonts/embed_assets.py from assets/: don't edit. */",
        "/* This file is part of openbv, under the GNU General Public License v3 or later. */",
        "#include \"embedded_assets.h\"",
        "",
    ]
    table = []
    for i, (src, name) in enumerate(FILES):
        im = Image.open(os.path.join(ROOT, src)).convert("RGBA")
        w, h = im.size
        # rows bottom-up, as the TGA stores them
        alpha = im.getchannel("A").transpose(Image.FLIP_TOP_BOTTOM).tobytes()
        packed = rle(alpha)
        lines.append(f"static const unsigned char asset{i}[{len(packed)}] = {{")
        for k in range(0, len(packed), 24):
            lines.append("  " + ",".join(str(b) for b in packed[k:k + 24]) + ",")
        lines.append("};")
        table.append(f"  {{\"{name}\", {w}, {h}, asset{i}, {len(packed)}}},")
    lines.append("")
    lines.append("const struct openbv_embedded openbv_embedded_assets[] = {")
    lines += table
    lines.append("  {0, 0, 0, 0, 0},")
    lines.append("};")
    out = os.path.join(ROOT, "src/port/embedded_assets.c")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(out)


if __name__ == "__main__":
    main()
