package proto

import (
	"bufio"
	"encoding/binary"
	"os"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

// The C structs and their Go counterparts. The layouts are checked against design/server.md
// Appendix A, which was generated by compiling the original headers (offsetof/sizeof).
var structs = map[string]any{
	"net_clsv_pong":                    ClsvPongMsg{},
	"net_clsv_spawn_request":           ClsvSpawnRequestMsg{},
	"net_clsv_player_shoot":            ClsvPlayerShootMsg{},
	"net_clsv_gameversion_accepted":    ClsvGameVersionAcceptedMsg{},
	"net_clsv_pickup_request":          ClsvPickupRequestMsg{},
	"net_clsv_admin_request":           ClsvAdminRequestMsg{},
	"net_clsv_vote":                    ClsvVoteMsg{},
	"net_clsv_map_list_request":        ClsvMapListRequestMsg{},
	"net_svcl_newplayer":               SvclNewPlayerMsg{},
	"net_svcl_server_info":             SvclServerInfoMsg{},
	"net_svcl_player_disconnect":       SvclPlayerDisconnectMsg{},
	"net_svcl_player_enum_state":       SvclPlayerEnumStateMsg{},
	"net_svcl_ping":                    SvclPingMsg{},
	"net_svcl_player_ping":             SvclPlayerPingMsg{},
	"net_svcl_player_spawn":            SvclPlayerSpawnMsg{},
	"net_svcl_sv_change":               SvclSvChangeMsg{},
	"net_svcl_player_shoot":            SvclPlayerShootMsg{},
	"net_svcl_delete_projectile":       SvclDeleteProjectileMsg{},
	"net_svcl_projectile_coord_frame":  SvclProjectileCoordFrameMsg{},
	"net_svcl_explosion":               SvclExplosionMsg{},
	"net_svcl_player_hit":              SvclPlayerHitMsg{},
	"net_svcl_play_sound":              SvclPlaySoundMsg{},
	"net_svcl_gameversion":             SvclGameVersionMsg{},
	"net_svcl_synchronize_timer":       SvclSynchronizeTimerMsg{},
	"net_svcl_change_flag_state":       SvclChangeFlagStateMsg{},
	"net_svcl_drop_flag":               SvclDropFlagMsg{},
	"net_svcl_flag_enum":               SvclFlagEnumMsg{},
	"net_svcl_round_state":             SvclRoundStateMsg{},
	"net_svcl_change_game_type":        SvclChangeGameTypeMsg{},
	"net_svcl_map_change":              SvclMapChangeMsg{},
	"net_svcl_pickup_item":             SvclPickupItemMsg{},
	"net_svcl_flame_stick_to_player":   SvclFlameStickToPlayerMsg{},
	"net_svcl_update_vote":             SvclUpdateVoteMsg{},
	"net_svcl_vote_result":             SvclVoteResultMsg{},
	"net_svcl_msg":                     SvclMsgMsg{},
	"net_svcl_player_update_stats":     SvclPlayerUpdateStatsMsg{},
	"net_svcl_bad_checksum_entity":     SvclBadChecksumEntityMsg{},
	"net_svcl_bad_checksum_info":       SvclBadChecksumInfoMsg{},
	"net_clsv_svcl_player_info":        PlayerInfoMsg{},
	"net_clsv_svcl_chat":               ChatMsg{},
	"net_clsv_svcl_team_request":       TeamRequestMsg{},
	"net_clsv_svcl_player_coord_frame": PlayerCoordFrameMsg{},
	"net_svcl_create_minibot":          SvclCreateMinibotMsg{},
	"net_svcl_minibot_coord_frame":     SvclMinibotCoordFrameMsg{},
	"net_clsv_svcl_player_change_name": PlayerChangeNameMsg{},
	"net_clsv_svcl_player_projectile":  PlayerProjectileMsg{},
	"net_clsv_svcl_player_shoot_melee": PlayerShootMeleeMsg{},
	"net_clsv_svcl_vote_request":       VoteRequestMsg{},
	"net_clsv_map_request":             ClsvMapRequestMsg{},
	"net_svcl_map_chunk":               SvclMapChunkMsg{},
	"net_svcl_map_list":                SvclMapListMsg{},
	"net_clsv_svcl_player_update_skin": PlayerUpdateSkinMsg{},
	"net_clsv_broadcast_query":         BroadcastQueryMsg{},
	"net_svcl_hash_seed":               HashSeedMsg{},
}

type field struct {
	offset, size int
	name         string
}

type layout struct {
	size   int
	fields []field
}

// appendixA reads the struct tables from the specification.
func appendixA(t *testing.T) map[string]layout {
	f, err := os.Open("../../../design/server.md")
	if err != nil {
		t.Fatalf("the specification: %v", err)
	}
	defer f.Close()
	head := regexp.MustCompile("^### `([a-zA-Z0-9_]+)` — ([0-9]+) bytes")
	row := regexp.MustCompile("^\\| ([0-9]+) \\| ([0-9]+) \\| `([a-zA-Z0-9_]+)` \\|")
	out := map[string]layout{}
	inAppendix := false
	cur := ""
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "## Appendix A") {
			inAppendix = true
			continue
		}
		if !inAppendix {
			continue
		}
		if m := head.FindStringSubmatch(line); m != nil {
			cur = m[1]
			n, _ := strconv.Atoi(m[2])
			out[cur] = layout{size: n}
			continue
		}
		if m := row.FindStringSubmatch(line); m != nil && cur != "" {
			off, _ := strconv.Atoi(m[1])
			sz, _ := strconv.Atoi(m[2])
			l := out[cur]
			l.fields = append(l.fields, field{off, sz, m[3]})
			out[cur] = l
		}
	}
	return out
}

func goLayout(v any) []field {
	tv := reflect.TypeOf(v)
	var out []field
	off := 0
	for i := 0; i < tv.NumField(); i++ {
		f := tv.Field(i)
		sz := binary.Size(reflect.Zero(f.Type).Interface())
		if f.Name != "_" {
			out = append(out, field{off, sz, f.Name})
		}
		off += sz
	}
	return out
}

func TestLayoutsMatchAppendixA(t *testing.T) {
	spec := appendixA(t)
	for cname, v := range structs {
		want, ok := spec[cname]
		if !ok {
			t.Errorf("%s: not in Appendix A", cname)
			continue
		}
		if got := binary.Size(v); got != want.size {
			t.Errorf("%s: size %d, Appendix A says %d", cname, got, want.size)
		}
		got := goLayout(v)
		if len(got) != len(want.fields) {
			t.Errorf("%s: %d fields, Appendix A has %d", cname, len(got), len(want.fields))
			continue
		}
		for i, w := range want.fields {
			g := got[i]
			if !strings.EqualFold(g.name, w.name) || g.offset != w.offset || g.size != w.size {
				t.Errorf("%s: field %d is %s@%d+%d, Appendix A: %s@%d+%d", cname, i, g.name, g.offset, g.size, w.name, w.offset, w.size)
			}
		}
	}
}

// Golden bytes: a coord frame as the client encodes it.
func TestCoordFrameBytes(t *testing.T) {
	m := PlayerCoordFrameMsg{PlayerID: 3, FrameID: 0x01020304, Position: [3]int16{150, -2, 25},
		Vel: [3]int8{-12, 5, 0}, MousePos: [3]int16{1, 2, 3}, BaboNetID: 7, CamPosZ: 9}
	b := Encode(&m)
	want := []byte{3, 0, 0, 0, 4, 3, 2, 1, 150, 0, 0xfe, 0xff, 25, 0, 0xf4, 5, 0, 0, 1, 0, 2, 0, 3, 0, 7, 0, 0, 0, 9, 0, 0, 0}
	if string(b) != string(want) {
		t.Fatalf("% x\nwant % x", b, want)
	}
	var back PlayerCoordFrameMsg
	Decode(b, &back)
	if back != m {
		t.Fatalf("round trip %+v", back)
	}
}

func TestDecodeShortIsZeroExtended(t *testing.T) {
	var m TeamRequestMsg
	Decode([]byte{5}, &m)
	if m.PlayerID != 5 || m.TeamRequested != 0 {
		t.Fatalf("%+v", m)
	}
}

func TestCStrings(t *testing.T) {
	var b [8]byte
	SetCString(b[:], "abcdefghij")
	if CString(b[:]) != "abcdefg" || b[7] != 0 {
		t.Fatalf("%q", b)
	}
}
